import { mphil, phd, ms, msds, bs } from "../../assets/images";

const academic = [
  {
    heading: "PhD",
    description:
      "PhD is the highest degree awarded in an academic discipline and is the most satisfying and rewarding educational experience. Students work closely with a faculty member, performing original research, and tackling challenging and unsolved problems",
    pic: phd,
    goto: "https://cs.qau.edu.pk/Phd.php",
  },
  {
    heading: "Mphil",
    description:
      "The objective of M.Phil Computer Science programme is to train students to initiate research work. The duration of M.Phil programme is two years (4 semesters).MPhil is of 50 credit hours, 24 credit hours for the course work and 26 credit hours for research work. Each course is of 3 credit hours.",
    pic: mphil,
    goto: "https://cs.qau.edu.pk/Phd.php",
  },
  {
    heading: "MS",
    description:
      "In today's Information Society, expertise in all forms of information is required for progress in science, business, and education. The main aim of MS programme in Information Science & Technology (IST) is to design and develop information related applications using information technology by understanding relationship between digital information, people and technology. The MS programme intends to bring together Computer Science and collaborative environment of how people and society interact with digital information MS (Information Science & Technology) Part Time (with 6 credit hours per semester) M.Sc.(Computer Science, Software Engineering, Information Technology) or 4 years BS (Computer Science, Software Engineering, Information Technology) with experience in digital information management",
    pic: ms,
    goto: "https://cs.qau.edu.pk/Phd.php",
  },
  {
    heading: "MS-DS",
    description:
      "Data Science has become an important due to the need for analyzing and understanding ever increasing data generated by a multitude of sources. By getting admission in the MS programme applicants will not only improve their qualifications but will also be equipped with the latest knowledge in the field. The students will be exposed to different aspects of data science including programming, data structures, and algorithms for data science, data analysis and visualization, and big data analytics. These aspects will provide the students the opportunities to effectively work in local and international markets as well as to pursue a PhD degree in data science. ",
    pic: msds,
    goto: "https://cs.qau.edu.pk/Phd.php",
  },
  {
    heading: "BS",
    description: `The BS Computer Science program at QAU provides a well-integrated balance of theoretical and practical knowledge required for developing reliable and usable software tools for different fields. The program enables students to design, implement and manage systems combining scientific, computational, communication and multimedia facilities in different domains. The main objective of the program is to provide students with a balanced breadth and depth of knowledge in Computer Science that enables them to begin their professional career in the software industry or they can continue their education at graduate level. In the final three semesters, students enhance their skills and knowledge in one of the following focus areas:
    Software Engineering
    Artificial Intelligence
    Data Science
    Platform based Development
    Human Centered Computing
    Networks and Security
    Information Management`,
    pic: bs,
    goto: "https://cs.qau.edu.pk/Phd.php",
  },
];

function Academic() {
  return (
    <div>
      <section className="px-5 py-24 text-white bg-accent-dark body-font">
        <div className="flex flex-col flex-wrap items-center w-full mb-20 text-center ">
          <h1 className="mb-2 text-2xl font-medium sm:text-3xl title-font ">
            Academics
          </h1>
          <p className="w-full leading-relaxed text-gray-300 lg:w-1/2">
            The department offers PhD, MPhil, MS (IST), M.Sc. and BS degrees
            <br />
            Each degree programme has a specific objective and focus.
            <br />
            The course of study and syllabi for each degree is updated and is
            inline its objectives.
          </p>
        </div>
        {academic.map((academics, index) => (
          <div
            key={index}
            className="container flex flex-col items-center mx-auto md:flex-row"
          >
            <div className="w-5/6 lg:max-w-lg lg:w-full md:w-1/2">
              <img
                className="object-cover object-center w-full h-full rouded "
                alt="hero"
                src={academics.pic}
              />
            </div>
            <div className="flex flex-col items-center mb-16 text-center lg:flex-grow md:w-1/2 lg:pl-28 md:pl-16 md:items-start md:text-left md:mb-0">
              <h1 className="mb-4 text-3xl font-medium title-font sm:text-4xl">
                {academics.heading}
              </h1>
              <p className="mb-8 leading-relaxed">{academics.description}</p>
              <div className="flex justify-center">
                <a
                  href={academics.goto}
                  className="inline-flex px-6 py-2 text-lg text-white transition-all duration-300 ease-in delay-100 border-0 rounded bg-primary focus:outline-none hover:bg-accent "
                >
                  See more
                </a>
              </div>
            </div>
          </div>
        ))}
      </section>
    </div>
  );
}

export default Academic;
